// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pg from "pg";

var config = {
  user: "testuser",
  password: "testpassword",
  host: "localhost",
  database: "testdatabase",
  port: 5432
};

test("Connect/disconnect w/o errors", (function () {
        var client = new Pg.Client(config);
        var __x = client.connect();
        return __x.then(function (param) {
                    return client.end();
                  });
      }));

test("Connect/disconnect w/o errors (no config)", (function () {
        var client = new Pg.Client(undefined);
        var __x = client.connect();
        return __x.then(function (param) {
                    return client.end();
                  });
      }));

export {
  config ,
  
}
/*  Not a pure module */
