// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pg from "../Pg.bs.js";

test("Connect/disconnect w/o errors", (function () {
        var client = Pg.Client.make("testuser", "testpassword", "localhost", "testdatabase", 5432, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
        var __x = client.connect();
        return __x.then(function (param) {
                    return client.end();
                  });
      }));

test("Connect/disconnect w/o errors (no config)", (function () {
        var client = Pg.Client.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
        var __x = client.connect();
        return __x.then(function (param) {
                    return client.end();
                  });
      }));

export {
  
}
/*  Not a pure module */
