// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pg = require("pg");
var Curry = require("rescript/lib/js/curry.js");
var Js_exn = require("rescript/lib/js/js_exn.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var Password = {};

var TypesParser = {};

var Config = {};

var QueryObject = {};

var QueryResult = {};

function make(user, password, host, database, port, connectionString, statement_timeout, query_timeout, application_name, connectionTimeoutMillis, idle_in_transaction_session_timeout, ssl, types, unit_) {
  var tmp = {};
  if (user !== undefined) {
    tmp.user = user;
  }
  if (password !== undefined) {
    tmp.password = Caml_option.valFromOption(password);
  }
  if (host !== undefined) {
    tmp.host = host;
  }
  if (database !== undefined) {
    tmp.database = database;
  }
  if (port !== undefined) {
    tmp.port = port;
  }
  if (connectionString !== undefined) {
    tmp.connectionString = connectionString;
  }
  if (statement_timeout !== undefined) {
    tmp.statement_timeout = statement_timeout;
  }
  if (query_timeout !== undefined) {
    tmp.query_timeout = query_timeout;
  }
  if (application_name !== undefined) {
    tmp.application_name = application_name;
  }
  if (connectionTimeoutMillis !== undefined) {
    tmp.connectionTimeoutMillis = connectionTimeoutMillis;
  }
  if (idle_in_transaction_session_timeout !== undefined) {
    tmp.idle_in_transaction_session_timeout = idle_in_transaction_session_timeout;
  }
  if (ssl !== undefined) {
    tmp.ssl = Caml_option.valFromOption(ssl);
  }
  if (types !== undefined) {
    tmp.types = Caml_option.valFromOption(types);
  }
  return new Pg.Client(tmp);
}

function query(client, parameters, queryString) {
  return client.query(queryString, parameters);
}

function toResult(err, res) {
  if (err == null) {
    if (res == null) {
      return Js_exn.raiseError("client.query(.., cb) has called the cb with neither error nor result");
    } else {
      return {
              TAG: /* Ok */0,
              _0: res
            };
    }
  } else {
    return {
            TAG: /* Error */1,
            _0: err
          };
  }
}

function queryCb(client, parameters, queryString, cb) {
  var tmp = {
    text: queryString
  };
  if (parameters !== undefined) {
    tmp.values = Caml_option.valFromOption(parameters);
  }
  client.query(tmp, (function (err, res) {
          return Curry._1(cb, toResult(err, res));
        }));
  
}

function queryObjCb(client, obj, cb) {
  client.query(obj, (function (err, res) {
          return Curry._1(cb, toResult(err, res));
        }));
  
}

var Client = {
  make: make,
  query: query,
  queryCb: queryCb,
  queryObjCb: queryObjCb
};

var $$instanceof = ((x, C) => x instanceof C);

function fromJsExn(exn) {
  if ($$instanceof(exn, Pg.DatabaseError)) {
    return Caml_option.some(exn);
  }
  
}

function fromExn(exn) {
  if (exn.RE_EXN_ID === Js_exn.$$Error) {
    return fromJsExn(exn._1);
  }
  
}

function DatabaseError_toJsExn(prim) {
  return prim;
}

var DatabaseError = {
  fromJsExn: fromJsExn,
  fromExn: fromExn,
  toJsExn: DatabaseError_toJsExn
};

exports.Password = Password;
exports.TypesParser = TypesParser;
exports.Config = Config;
exports.QueryObject = QueryObject;
exports.QueryResult = QueryResult;
exports.Client = Client;
exports.DatabaseError = DatabaseError;
/* pg Not a pure module */
