version: 2
updates:
  - package-ecosystem: "npm"
    allow: "direct"
    reviewers: ["rpominov"]
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "chalk"
        versions: ["5.x"]
