// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function stringifyAnySafe(val) {
  var str;
  try {
    str = JSON.stringify(val);
  }
  catch (exn){
    return String(val);
  }
  if (str !== undefined) {
    return str;
  } else {
    return String(val);
  }
}

function toString(message) {
  return message.map(function (node) {
                switch (node.TAG | 0) {
                  case /* Text */0 :
                      return node._0;
                  case /* MessageOf */1 :
                      return node._0.message;
                  case /* StackOf */2 :
                      return node._0.stack;
                  case /* Exn */3 :
                  case /* Obj */4 :
                      return stringifyAnySafe(node._0);
                  
                }
              }).join(" ");
}

exports.stringifyAnySafe = stringifyAnySafe;
exports.toString = toString;
/* No side effect */
