// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var isInstanceOfError = ((x) => x instanceof Error);

function code(err) {
  var opt = err.code;
  if (opt !== undefined && typeof opt === "string") {
    return opt;
  }
  
}

function fromJsExn(exn) {
  if (isInstanceOfError(exn)) {
    return Caml_option.some(exn);
  }
  
}

function fromExn(exn) {
  if (exn.RE_EXN_ID === Js_exn.$$Error) {
    return fromJsExn(exn._1);
  }
  
}

var toExn = Js_exn.anyToExnInternal;

exports.code = code;
exports.fromJsExn = fromJsExn;
exports.fromExn = fromExn;
exports.toExn = toExn;
/* No side effect */
