// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("@rpominov/rescript-promise/lib/js/Promise.bs.js");
var Process = require("process");

function progress(promise) {
  return $$Promise.chain(promise, (function (x) {
                if (x.TAG === /* Ok */0) {
                  Process.stdout.write(".");
                }
                return $$Promise.resolve(x);
              }));
}

exports.progress = progress;
/* Promise Not a pure module */
