// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Net = require("net");

var BufferOrString = {};

var Socket = {};

var Net$1 = {
  BufferOrString: BufferOrString,
  Socket: Socket
};

function make(param) {
  return {
          buf: Buffer.alloc(128),
          offset: 0
        };
}

function writeInt(message, value) {
  var offset$p = message.buf.writeInt32LE(value, message.offset);
  return {
          buf: message.buf,
          offset: message.offset + offset$p | 0
        };
}

function writeInt8(message, value) {
  var offset$p = message.buf.writeUInt8(value, message.offset);
  return {
          buf: message.buf,
          offset: message.offset + offset$p | 0
        };
}

function writeString(message, value) {
  var offset$p = message.buf.write(value, message.offset);
  return {
          buf: message.buf,
          offset: message.offset + offset$p | 0
        };
}

var Message = {
  make: make,
  writeInt: writeInt,
  writeInt8: writeInt8,
  writeString: writeString
};

var socket = Net.connect("5432", "localhost");

socket.on("close", (function (hadError) {
          console.log("TCP connection closed. Had error:", hadError);
          
        })).on("ready", (function (param) {
        console.log("TCP connection established");
        socket.on("data", (function (data) {
                  console.log("Data received:", data.toString());
                  
                })).on("error", (function (error) {
                console.log("TCP error:", error);
                
              }));
        var message_buf = Buffer.alloc(128);
        var message = {
          buf: message_buf,
          offset: 0
        };
        var message$1 = writeInt(message, 196608);
        var message$2 = writeString(message$1, "user");
        var message$3 = writeString(message$2, "roman");
        var message$4 = writeInt8(message$3, 0);
        var message$5 = writeString(message$4, "database");
        var message$6 = writeString(message$5, "roman");
        var message$7 = writeInt8(message$6, 0);
        var message$8 = writeInt8(message$7, 0);
        console.log(socket.write(message$8.buf));
        
      }));

var connectionSettings = {
  host: "localhost",
  port: "5432",
  user: "roman",
  pass: "1234",
  database: "roman"
};

exports.Net = Net$1;
exports.Message = Message;
exports.connectionSettings = connectionSettings;
exports.socket = socket;
/* socket Not a pure module */
