// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("rescript-jest/lib/js/Jest.bs.js");
var Parser$ExtendedSQL = require("../Parser.bs.js");
var Printer$ExtendedSQL = require("../Printer.bs.js");

Jest.each([
      "SELECT 1",
      "-- inline\nSELECT /* block */1",
      "SELECT :foo = :bar",
      "SELECT :num:raw<1|2>",
      "SELECT :num:raw<1,|> 2",
      "SELECT :num:raw<<<'<|>'|||'2'>>>",
      "INSERT INTO test (foo, bar) VALUES :values:batch<(:foo, :bar)>",
      "INSERT INTO test (foo, bar) VALUES :values:batch<<(:foo:batch<:bar>)>>",
      "INSERT INTO test (foo, bar) VALUES :values:batch<<(:foo:raw<foo|bar>)>>",
      "INSERT INTO test (foo, bar) VALUES :values:batch<<(:foo /* <comment> */)>>"
    ], "%s", (function (code) {
        expect(Printer$ExtendedSQL.print(undefined, Jest.getOkExn(Parser$ExtendedSQL.parse(code), "File \"Printer.test.res\", line 17, characters 40-47").ast)).toMatchSnapshot();
        
      }));

/*  Not a pure module */
