// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Parser$ExtendedSQL = require("../Parser.bs.js");

test("Simplest query", (function () {
        expect(Parser$ExtendedSQL.parse("SELECT 1")).toMatchSnapshot();
        
      }));

/*  Not a pure module */
