// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TTY$Builder = require("./TTY.bs.js");

function build(ctx) {
  return TTY$Builder.info(ctx, "TODO: build");
}

function watch(ctx) {
  return TTY$Builder.info(ctx, "TODO: watch");
}

function pipe(ctx) {
  return TTY$Builder.info(ctx, "TODO: pipe");
}

exports.build = build;
exports.watch = watch;
exports.pipe = pipe;
/* No side effect */
