// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var GeneratorInputData = {};

function quiet(ctx) {
  if (ctx.argv.quiet) {
    return true;
  } else {
    return ctx.config.quiet === true;
  }
}

exports.GeneratorInputData = GeneratorInputData;
exports.quiet = quiet;
/* No side effect */
