// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Context$Builder = require("./Context.bs.js");

function info(ctx, val0) {
  if (!Context$Builder.quiet(ctx)) {
    console.error(val0);
    return ;
  }
  
}

function info2(ctx, val0, val1) {
  if (!Context$Builder.quiet(ctx)) {
    console.error(val0, val1);
    return ;
  }
  
}

function info3(ctx, val0, val1, val2) {
  if (!Context$Builder.quiet(ctx)) {
    console.error(val0, val1, val2);
    return ;
  }
  
}

function infoNl(ctx) {
  return info(ctx, "");
}

exports.info = info;
exports.info2 = info2;
exports.info3 = info3;
exports.infoNl = infoNl;
/* No side effect */
