// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_splice_call = require("rescript/lib/js/caml_splice_call.js");
var Steps$TypesafeSqlBuilder = require("./Steps.bs.js");
var Promise$TypesafeSqlBuilder = require("./Promise.bs.js");
var DescribeQuery = require("@typesafe-sql/describe-query");

function main(client) {
  return Promise$TypesafeSqlBuilder.chain(Promise$TypesafeSqlBuilder.chainOk(Promise$TypesafeSqlBuilder.chainOk(Promise$TypesafeSqlBuilder.chainOk(Steps$TypesafeSqlBuilder.Read.read("./src/example.sql"), Steps$TypesafeSqlBuilder.Parse.asyncParse), (function (parsed) {
                        return Promise$TypesafeSqlBuilder.chainOk(Steps$TypesafeSqlBuilder.Describe.describeMany(client, parsed.map(function (x) {
                                            return x.processedStatement;
                                          })), (function (__x) {
                                      return Steps$TypesafeSqlBuilder.Generate.generate(parsed, __x, Steps$TypesafeSqlBuilder.Generate.exampleGenerator);
                                    }));
                      })), (function (__x) {
                    return Steps$TypesafeSqlBuilder.Write.write("./src/example.json", __x);
                  })), (function (result) {
                if (result.TAG !== /* Ok */0) {
                  Caml_splice_call.spliceApply(console.error, [result._0.msg]);
                }
                return Promise$TypesafeSqlBuilder.resolve(undefined);
              }));
}

Promise$TypesafeSqlBuilder.done(DescribeQuery.createClient({
          user: "testuser",
          password: "testpassword",
          host: "localhost",
          database: "testdatabase"
        }), (function (client) {
        return Promise$TypesafeSqlBuilder.done(main(client), (function (param) {
                      client.terminate();
                      
                    }));
      }));

var DescribeQuery$1;

exports.DescribeQuery = DescribeQuery$1;
exports.main = main;
/*  Not a pure module */
