// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var TypesafeSQLDescribeQuery = require("@typesafe-sql/rescript-describe-query/lib/js/TypesafeSQLDescribeQuery.bs.js");
var Parser$TypesafeSqlBuilder = require("./Parser.bs.js");
var Promise$TypesafeSqlBuilder = require("./Promise.bs.js");

function processFileContent(client, text, cb) {
  var statements = text.split(";").map(function (prim) {
          return prim.trim();
        }).filter(function (val) {
        return val !== "";
      });
  var helper = function (index, results) {
    if (index >= statements.length) {
      return Curry._1(cb, {
                  TAG: /* Ok */0,
                  _0: results
                });
    }
    var match = Parser$TypesafeSqlBuilder.parseStatement(Caml_array.get(statements, index));
    if (match.TAG !== /* Ok */0) {
      return Curry._1(cb, {
                  TAG: /* Error */1,
                  _0: "The following statement is missing a name declaration. Did you forget to add a \"-- @someName\" comment?\n\n" + Caml_array.get(statements, index)
                });
    }
    var match$1 = match._0;
    var text = match$1[2];
    var parameters = match$1[1];
    var name = match$1[0];
    return Promise$TypesafeSqlBuilder.subscribe(client.describe(text), (function (val) {
                  if (val.TAG === /* Ok */0) {
                    return helper(index + 1 | 0, results.concat([{
                                      name: name,
                                      parameters: parameters,
                                      text: text,
                                      description: val._0
                                    }]));
                  } else {
                    return Curry._1(cb, {
                                TAG: /* Error */1,
                                _0: "Database server could not process the following statement:\n\n" + text + "\n\n" + TypesafeSQLDescribeQuery.errorToString(val._0)
                              });
                  }
                }));
  };
  return helper(0, []);
}

var DescribeQuery;

var A;

var S;

exports.DescribeQuery = DescribeQuery;
exports.A = A;
exports.S = S;
exports.processFileContent = processFileContent;
/* Promise-TypesafeSqlBuilder Not a pure module */
