// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_exn = require("rescript/lib/js/js_exn.js");
var Process = require("process");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

function crash(exn) {
  var jsExn = Caml_js_exceptions.caml_as_js_exn(exn);
  if (jsExn !== undefined) {
    console.error(Caml_option.valFromOption(jsExn));
  } else {
    console.error(exn);
  }
  return Process.exit(1);
}

function chain(promise, callback) {
  return promise.then(function (val) {
              try {
                return Curry._1(callback, val);
              }
              catch (raw_exn){
                return crash(Caml_js_exceptions.internalToOCamlException(raw_exn));
              }
            });
}

function subscribe(promise, callback) {
  promise.then((function (val) {
          try {
            return Curry._1(callback, {
                        TAG: /* Ok */0,
                        _0: val
                      });
          }
          catch (raw_exn){
            return crash(Caml_js_exceptions.internalToOCamlException(raw_exn));
          }
        }), (function (error) {
          try {
            return Curry._1(callback, {
                        TAG: /* Error */1,
                        _0: Js_exn.anyToExnInternal(error)
                      });
          }
          catch (raw_exn){
            return crash(Caml_js_exceptions.internalToOCamlException(raw_exn));
          }
        }));
  
}

exports.chain = chain;
exports.subscribe = subscribe;
/* process Not a pure module */
