// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("rescript-jest/lib/js/Jest.bs.js");
var Util$Errors = require("../Util.bs.js");

var realWorld = "if i < start {\n      highlightSymbols.contents->Js.Array2.push(_)->ignore\n    } else if i <= end {\n      highlightSymbols.contents->Js.Array2.push(_)->ignore\n      highlightSymbolsEmpty := false\n    }\n";

Jest.each3([
      [
        "abc",
        0,
        0
      ],
      [
        "abc",
        3,
        3
      ],
      [
        "abc",
        4,
        4
      ],
      [
        realWorld,
        21,
        95
      ],
      [
        ">> ☀︎ <<",
        2,
        4
      ]
    ], "%p %p %p", (function (code, start, end) {
        expect(Util$Errors.highlight(code, start, end)).toMatchSnapshot();
        
      }));

exports.realWorld = realWorld;
/*  Not a pure module */
