name: Audit

on:
  push:
    branches: [master]
    paths:
      - "package.json"
      - "package-lock.json"
      - ".sdccheckignore"
      - "audit.yml"
  pull_request:
    branches: [master]
    paths:
      - "package.json"
      - "package-lock.json"
      - ".sdccheckignore"
      - "audit.yml"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: NodeSecure CI
        uses: NodeSecure/ci-action@v1
        with:
          strategy: npm
          vulnerabilities: medium
          warnings: warning
          reporters: console

      - name: Run sdc-check
        uses: rpominov/sdc-check-action@v3
