name: Security audit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: NodeSecure CI
        uses: NodeSecure/ci-action@v1
        with:
          strategy: npm
          vulnerabilities: medium
          warnings: warning
          reporters: console

      - name: Run sdc-check
        uses: rpominov/sdc-check-action@main

      - run: npm ci
      - run: npm run build:ci
