name: Backup

on:
  push:
    branches: [master]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Backup to BitBucket
        uses: rpominov/git-backup-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
          REMOTE: "git@bitbucket.org:rpominov/typesafe-sql_backup.git"
