name: Repository backup

on:
  push:
    branches:
    - master

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: rpominov/git-backup-action@v1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        REMOTE: "git@bitbucket.org:rpominov/typesafe-sql_backup.git"
